demo = (
""".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""
).splitlines()

splits = 0
with open("day-7/input.txt") as f:
    tachyon_state = [char == "S" for char in f.readline()[:-1]]  # get rid of the line break
    for line in f.readlines():
        for i in range(len(line[:-1])):
            if tachyon_state[i]:
                if line[i] == "^":
                    if i != 0:
                        tachyon_state[i - 1] = True
                    tachyon_state[i] = False
                    if i != (len(line) - 2):
                        tachyon_state[i + 1] = True
                    splits += 1

splits
